apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment-leader
  labels:
    app: locust-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-leader
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-leader
    spec:
      containers:
      - name: locust-leader
        image: cade/donate-locust@sha256:d5c2e29a12b93e1acd818f7fa049c4930824750d14813945aa3abd23d3c426eb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        - containerPort: 5557
        - containerPort: 5558
        env:
          - name: TARGET_URL
            valueFrom:
              configMapKeyRef:
                name: donate-locust-config
                key: targeturl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
