apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment-follower
  labels:
    app: locust-follower
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-follower
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-follower
    spec:
      containers:
      - name: locust-follower
        image: cade/donate-locust@sha256:bd33eaea3faafa58b682b38b4277287a12ec0b2d7bce1c34afdc4aade5164136
        imagePullPolicy: IfNotPresent
        env:
          - name: TARGET_URL
            valueFrom:
              configMapKeyRef:
                name: donate-locust-config
                key: targeturl
          - name: LOCUST_LEADER_HOST
            value: donate-locust
          - name: LOCUST_LEADER_PORT
            value: '5557'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
